### ISSUE TITLE
Choose testing framework

### ISSUE THREAD

**Issue by dgasull** [bsc-dom/dataclay-packaging#25]
Refers to https://github.com/bsc-dom/dataclay-packaging/issues/6

**Comment by daniwhere** [comment]
We should cover the following: 

* **Functional tests**: we will use either **CircleCI**, **Travis**, **Appvoyer** or **Jenkins** to deploy dataclay services and run functional tests: 
    * Our services will be deployed using **docker-compose** 
    * We should do some tests of communications in different networks... 
    * **Code coverage**: our tools should analyze covered code 
* **Unitary tests**: we will use **JUnit** and **pytest** managed by **Maven** and **TOX** (which, will be also managed by our *testing integration tool* before)
    * **Mocking**: we will need to use third-party libraries to mock our classes
    * **Mutation tests**: testing Mutation Testing is a type of software testing where we mutate (change) certain statements in the source code and check if the test cases are able to find the errors. The goal of Mutation Testing is to assess the quality of the test cases which should be robust enough to fail mutant code. We saw **PITEST** and **mutmut** libraries, we will decide it later.
* **System tests**: we will use same tools than for Functional tests: 
    * Take into account our supported architectures:  currently armv7 and amd64 
    * Check if we need to do anything different than docker for Windows, Mac or other OSs. 
* **BDDs**: Finally we will have a tool like **Cucumber** to define our functional/behaviours in an easy way so we know what is tested and what is not.  

Next step is to decide which is our main continous integration tool, define a pipeline (nightly builds,...) @alexbarcelo @pierlauro 

Once we decide it, we will configure it (among with cucumber probably) and run some unitary tests we have. Then we will decide if we start doing Mocking and better unitary tests (easy to develop and try) or we create BDDs and we create them on demand.

**Comment by daniwhere** [comment]
Finally we decided to use **Travis** because: 
- CircleCI pricing (actually not free) 
- Jenkins requires you to host 
- Appvoyer has less concurrent jobs
