### ISSUE TITLE
Support for newVersion onto Python objects

### ISSUE THREAD

**Issue by alexbarcelo** [bsc-dom/dataclay-packaging#33]
newVersion feature hasn't been properly implemented nor tested for Python objects

**Comment by alexbarcelo** [comment]
bsc-dom/javaclay/issues/26
bsc-dom/pyclay/issues/33

**Comment by daniwhere** [comment]
Support finished. Functional testing for new version in pyclay can be found [here](https://github.com/bsc-dom/dataclay-functional-testing/blob/main/features/new-version-consolidate.feature)

Closing issue.
