### ISSUE TITLE
Nightly builds or snapshots

### ISSUE THREAD

**Issue by dgasull** [bsc-dom/dataclay-packaging#37]
Decide to use nightly builds or run tests in last available package in maven, pypi and dockers. Any votes?

This is associated to epic https://github.com/bsc-dom/dataclay-packaging/issues/6

**Comment by daniwhere** [comment]
I guess that since docker build can be expensive we should do it nightly, and also, we could implement some mechanism to, once a PR in pyclay and javaclay is accepted, cron in packaging is updating the submodules -- that should be a reason for a nightly build instead a merge build

**Comment by pierlauro** [comment]
> I guess that since docker build can be expensive we should do it nightly, and also, we could implement some mechanism to, once a PR in pyclay and javaclay is accepted, cron in packaging is updating the submodules -- that should be a reason for a nightly build instead a merge build

Agree with that!
