### ISSUE TITLE
Implement testing system 

### ISSUE THREAD

**Issue by dgasull** [bsc-dom/dataclay-packaging#74]
Refers to Epic https://github.com/bsc-dom/dataclay-packaging/issues/6 

Create repository that test current packages in development (dockers, pypi and maven) using BDD functional tests. 

Tests will be developed using `cucumber` and python `behave`. Reports will be published in github.io , one tool could be `allure`. 

Tests will run tests using current published dev packages in different environments and architectures (arm, amd64, ...) . For that we will use `travis` matrix.

Functional tests should be grouped in `travis jobs` and may take maximum 50 minutes. 

Orchestration of dataClay for each test still under design. We could use bash scripts that execute `docker-compose up` or any needed docker command; bash scripts could be reused in orchestration repository in the future (current only using singularity).

Java functional test can be "prepared" using python `behave` (deployment, new account, contracts, ...) and using `jpype` we could call each Java specific step. @alexbarcelo what do you think? This could allow us to have more reusability of code. Another option is to create two different `feature` files, one for Java and one for Python (and then use `cucumber-jvm` for Java and `behave` for Python) **but is not conceptually correct that a feature depends on the environment (is like creating features for OS)**  

Final structure would be: 
```
.
├── make-persistent
│   ├── docker-compose.yml  (maybe as a docstring in feature)
│   ├── environment.py (include calls to test-orchestration)
│   ├── java
│   │   ├── app
│   │   │   ├── cfgfiles
│   │   │   └── src
│   │   └── model
│   ├── make-persistent.feature
│   ├── python
│   │   ├── app
│   │   │   ├── cfgfiles
│   │   │   └── src
│   │   │       └── hellopeople.py
│   │   └── model
│   │       └── src
│   │           ├── classes.py
│   │           └── __init__.py
│   └── steps
│       └── make-persistent.py
└── test-orchestration
    └── orchestrate.sh
```

**Comment by alexbarcelo** [comment]
I like the idea of using a single codebase for orchestration (be it `behave` in Python with jpype or its symmetric option which would be `cucumber-jvm` with Jython).

If you think that it is achievable, I would go for it. If down the road we need to change it, then so be it. Having two different feature files is a last resort --as you say, I believe it is an antipattern.

I understand (if I remember correctly? I think we commented on that f2f) that the registration step would be described in the step. With all that in mind, the general structure seems good. Only thing: will we need to make the number of dataservices parametric? I am wondering about the docker-compose file / definition. But unless we see a clear use case for changing that, your described structure seems a good starting point. Making it a docstring would make it configurable, but decrease readability of the tests... at a first glance, I may avoid that and keep it as a file instead.
