### ISSUE TITLE
GC no cleaning distributed objects with circular references

### ISSUE THREAD

**Issue by dgasull** [bsc-dom/dataclay-packaging#87]
We have two Storage Locations, with two objecs A and B where A references B and B references A. When those objects are not accessible, they should be cleaned by the GC but they're currently not. 

When the DS1 GC finds out that object A is candidate to be cleaned, it is marked as 'unaccessible' and all references objects from A should receive a "-1" ref. counting. GC notifies DS2 that B has -1 reference. In the next iteration, GC realizes that A has 1 reference, so it is not an 'unaccessible' candidate anymore and A is marked as 'accessible', so GC should notify DS2 +1 reference to B. 

If, during -1 notification, DS2 processes candidate B and notifies -1 to DS1, then objects are properly removed, however, this cannot be guaranteed, so if DS2 processes the -1 notification and notifies -1 later, then the objects are never cleaned. 

This is not happening if the cycle is distributed. 

Any ideas on how to fix that? @alexbarcelo

**Comment by daniwhere** [comment]
Fixed in https://github.com/bsc-dom/dataclay-packaging/commit/ce843eb367cd1c4b7b925753f51624fa9d7cced9 

Finally we've designed a distributed graph to allow circular references detection.
